# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\iojkp\OneDrive\桌面\NN2\110522160_劉秉澤_作業二\RBFN.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 732)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(130, 20, 481, 461))
        self.graphicsView.setObjectName("graphicsView")
        self.Train = QtWidgets.QPushButton(self.centralwidget)
        self.Train.setGeometry(QtCore.QRect(200, 620, 111, 51))
        self.Train.setObjectName("Train")
        self.Walk = QtWidgets.QPushButton(self.centralwidget)
        self.Walk.setGeometry(QtCore.QRect(500, 560, 111, 111))
        self.Walk.setObjectName("Walk")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 500, 591, 41))
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 759, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Train.setText(_translate("MainWindow", "Training"))
        self.Walk.setText(_translate("MainWindow", "Run"))
